folderin: /home/yuliya/PycharmProjects/pythonProject/LinuxSeminar3/in
folderout: /home/yuliya/PycharmProjects/pythonProject/LinuxSeminar3/out
folderext: /home/yuliya/PycharmProjects/pythonProject/LinuxSeminar3/folder
count: 5
bs: 1M
type: zip